// GENERATED BY tool/generate_northstar_icon_manifest.dart — DO NOT EDIT.

import 'northstar_icon_category.dart';
import 'northstar_icon_manifest_item.dart';

/// All bundled Northstar V3 SVGs under `assets/northstar_icons/`.
const List<NorthstarIconManifestItem> kNorthstarIconManifest = 
    <NorthstarIconManifestItem>[
  NorthstarIconManifestItem(
    id: 'calendar',
    relativeAssetPath: 'assets/northstar_icons/Calendar.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'emblem',
    relativeAssetPath: 'assets/northstar_icons/Emblem.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bell-time',
    relativeAssetPath: 'assets/northstar_icons/Icon=bell-time.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-group',
    relativeAssetPath: 'assets/northstar_icons/Icon=calendar-group.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-heart',
    relativeAssetPath: 'assets/northstar_icons/Icon=calendar-heart.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-2',
    relativeAssetPath: 'assets/northstar_icons/Icon=calendar.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'chat-alert',
    relativeAssetPath: 'assets/northstar_icons/Icon=chat-alert.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'chat-edit',
    relativeAssetPath: 'assets/northstar_icons/Icon=chat-edit.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'clock-add',
    relativeAssetPath: 'assets/northstar_icons/Icon=clock-add.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'clock-group',
    relativeAssetPath: 'assets/northstar_icons/Icon=clock-group.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'clock',
    relativeAssetPath: 'assets/northstar_icons/Icon=clock.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'directory-team',
    relativeAssetPath: 'assets/northstar_icons/Icon=directory-team.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'document-approve',
    relativeAssetPath: 'assets/northstar_icons/Icon=document-approve.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-group',
    relativeAssetPath: 'assets/northstar_icons/Icon=document-group.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-lock',
    relativeAssetPath: 'assets/northstar_icons/Icon=document-lock.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document',
    relativeAssetPath: 'assets/northstar_icons/Icon=document.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'gift',
    relativeAssetPath: 'assets/northstar_icons/Icon=gift.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'leave-team',
    relativeAssetPath: 'assets/northstar_icons/Icon=leave-team.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'leave',
    relativeAssetPath: 'assets/northstar_icons/Icon=leave.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'lock',
    relativeAssetPath: 'assets/northstar_icons/Icon=lock.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'megaphone',
    relativeAssetPath: 'assets/northstar_icons/Icon=megaphone.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'office-building',
    relativeAssetPath: 'assets/northstar_icons/Icon=office-building.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'question-circle',
    relativeAssetPath: 'assets/northstar_icons/Icon=question-circle.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'thumbnail',
    relativeAssetPath: 'assets/northstar_icons/Icon=thumbnail.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'timezone',
    relativeAssetPath: 'assets/northstar_icons/Icon=timezone.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'user-group',
    relativeAssetPath: 'assets/northstar_icons/Icon=user-group.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'user-time',
    relativeAssetPath: 'assets/northstar_icons/Icon=user-time.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'user',
    relativeAssetPath: 'assets/northstar_icons/Icon=user.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'work-time',
    relativeAssetPath: 'assets/northstar_icons/Icon=work-time.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'telegram',
    relativeAssetPath: 'assets/northstar_icons/Property 1=Telegram.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'x',
    relativeAssetPath: 'assets/northstar_icons/Property 1=X.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'align-center-justify',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-center-justify.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-center',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-center.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-left-justify',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-left-justify.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-left',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-left.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-right-justify',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-right-justify.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-right',
    relativeAssetPath: 'assets/northstar_icons/Property 1=align-right.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'atom',
    relativeAssetPath: 'assets/northstar_icons/Property 1=atom.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'bold',
    relativeAssetPath: 'assets/northstar_icons/Property 1=bold.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'brain',
    relativeAssetPath: 'assets/northstar_icons/Property 1=brain.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'code',
    relativeAssetPath: 'assets/northstar_icons/Property 1=code.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'ellipsis',
    relativeAssetPath: 'assets/northstar_icons/Property 1=ellipsis.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'facebook-messenger',
    relativeAssetPath: 'assets/northstar_icons/Property 1=facebook-messenger.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'facebook',
    relativeAssetPath: 'assets/northstar_icons/Property 1=facebook.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'font',
    relativeAssetPath: 'assets/northstar_icons/Property 1=font.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'foundation',
    relativeAssetPath: 'assets/northstar_icons/Property 1=foundation.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'heading',
    relativeAssetPath: 'assets/northstar_icons/Property 1=heading.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'instagram',
    relativeAssetPath: 'assets/northstar_icons/Property 1=instagram.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'italic',
    relativeAssetPath: 'assets/northstar_icons/Property 1=italic.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'linkedin',
    relativeAssetPath: 'assets/northstar_icons/Property 1=linkedin.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'list-ol',
    relativeAssetPath: 'assets/northstar_icons/Property 1=list-ol.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'list-ul',
    relativeAssetPath: 'assets/northstar_icons/Property 1=list-ul.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'medical',
    relativeAssetPath: 'assets/northstar_icons/Property 1=medical.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'molecule',
    relativeAssetPath: 'assets/northstar_icons/Property 1=molecule.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'organism',
    relativeAssetPath: 'assets/northstar_icons/Property 1=organism.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'redo',
    relativeAssetPath: 'assets/northstar_icons/Property 1=redo.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'spinner',
    relativeAssetPath: 'assets/northstar_icons/Property 1=spinner.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'template',
    relativeAssetPath: 'assets/northstar_icons/Property 1=template.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'text-size',
    relativeAssetPath: 'assets/northstar_icons/Property 1=text-size.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'text-strike-through',
    relativeAssetPath: 'assets/northstar_icons/Property 1=text-strike-through.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'underline',
    relativeAssetPath: 'assets/northstar_icons/Property 1=underline.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'undo',
    relativeAssetPath: 'assets/northstar_icons/Property 1=undo.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'youtube',
    relativeAssetPath: 'assets/northstar_icons/Property 1=youtube.svg',
    category: NorthstarIconCategory.social,
  ),
  NorthstarIconManifestItem(
    id: 'rectangle-2',
    relativeAssetPath: 'assets/northstar_icons/Rectangle 2.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'science-brain',
    relativeAssetPath: 'assets/northstar_icons/Science/brain.svg',
    category: NorthstarIconCategory.science,
  ),
  NorthstarIconManifestItem(
    id: 'align-bottom',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=align-bottom.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'align-top',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=align-top.svg',
    category: NorthstarIconCategory.content,
  ),
  NorthstarIconManifestItem(
    id: 'arrow-down',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=arrow-down.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'arrow-from-right',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=arrow-from-right.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'arrow-left',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=arrow-left.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'arrow-right',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=arrow-right.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'arrow-up',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=arrow-up.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-heart-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=calendar-heart.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-3',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=calendar.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-down',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-down.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-left',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-left.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-leftdouble',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-leftdouble.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-right',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-right.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-rightdouble',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-rightdouble.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'chevron-up',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=chevron-up.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'circle-down',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=circle-down.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'circle-left',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=circle-left.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'circle-right',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=circle-right.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'circle-up',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=circle-up.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'compress',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=compress.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'download-1',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=download-1.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'download-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=download-2.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'exchange',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=exchange.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'exit',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=exit.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'expand-arrow',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=expand-arrow.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'expand',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=expand.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'login',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=login.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'logout',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=logout.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'reload',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=reload.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'retracted',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=retracted.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'scroll-select',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=scroll-select.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'sort-down',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=sort-down.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'sort-up',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=sort-up.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'time-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=time-2.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'time-add',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=time-add.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'time',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=time.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'upload-1',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=upload-1.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'upload-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=upload-2.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'withdraw',
    relativeAssetPath: 'assets/northstar_icons/Solid=No, Value=withdraw.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'calendar-4',
    relativeAssetPath: 'assets/northstar_icons/Solid=Yes, Value=calendar.svg',
    category: NorthstarIconCategory.calendar,
  ),
  NorthstarIconManifestItem(
    id: 'time-2-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=Yes, Value=time-2.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'time-2',
    relativeAssetPath: 'assets/northstar_icons/Solid=Yes, Value=time.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'type',
    relativeAssetPath: 'assets/northstar_icons/Type.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'tool',
    relativeAssetPath: 'assets/northstar_icons/Value=Tool, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'add-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=add chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'add-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=add chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'add',
    relativeAssetPath: 'assets/northstar_icons/Value=add, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'add-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=add-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'add-square',
    relativeAssetPath: 'assets/northstar_icons/Value=add-square, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'alert-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=alert chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'alert-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=alert chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'approve-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=approve chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'approve-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=approve chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'archive',
    relativeAssetPath: 'assets/northstar_icons/Value=archive, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'assessment-requested',
    relativeAssetPath: 'assets/northstar_icons/Value=assessment-requested.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'attach',
    relativeAssetPath: 'assets/northstar_icons/Value=attach, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'award',
    relativeAssetPath: 'assets/northstar_icons/Value=award, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'award-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=award-alt, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'back',
    relativeAssetPath: 'assets/northstar_icons/Value=back, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'ban',
    relativeAssetPath: 'assets/northstar_icons/Value=ban, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bank',
    relativeAssetPath: 'assets/northstar_icons/Value=bank, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'bar-graph-box',
    relativeAssetPath: 'assets/northstar_icons/Value=bar graph-box, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'bar-graph-irregular',
    relativeAssetPath: 'assets/northstar_icons/Value=bar graph-irregular, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'bar-graph-regular',
    relativeAssetPath: 'assets/northstar_icons/Value=bar graph-regular, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'bell',
    relativeAssetPath: 'assets/northstar_icons/Value=bell, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bell-off',
    relativeAssetPath: 'assets/northstar_icons/Value=bell-off, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bill',
    relativeAssetPath: 'assets/northstar_icons/Value=bill, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'blank-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=blank chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'blank-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=blank chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'book-open',
    relativeAssetPath: 'assets/northstar_icons/Value=book-open, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bookmark',
    relativeAssetPath: 'assets/northstar_icons/Value=bookmark, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bookmark-2',
    relativeAssetPath: 'assets/northstar_icons/Value=bookmark, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'bullet-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=bullet chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'bullet-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=bullet chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'burger',
    relativeAssetPath: 'assets/northstar_icons/Value=burger, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'calculator',
    relativeAssetPath: 'assets/northstar_icons/Value=calculator, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'camera',
    relativeAssetPath: 'assets/northstar_icons/Value=camera, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'camera-add',
    relativeAssetPath: 'assets/northstar_icons/Value=camera-add, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'chart-bar-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=chart-bar-alt, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'chats',
    relativeAssetPath: 'assets/northstar_icons/Value=chats, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'check',
    relativeAssetPath: 'assets/northstar_icons/Value=check, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'check-box',
    relativeAssetPath: 'assets/northstar_icons/Value=check-box, Filled=No.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'check-box-2',
    relativeAssetPath: 'assets/northstar_icons/Value=check-box, Filled=Yes.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'check-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=check-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'check-circle-2',
    relativeAssetPath: 'assets/northstar_icons/Value=check-circle, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'clapper',
    relativeAssetPath: 'assets/northstar_icons/Value=clapper, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'clipboard-notes',
    relativeAssetPath: 'assets/northstar_icons/Value=clipboard-notes.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'close',
    relativeAssetPath: 'assets/northstar_icons/Value=close, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'close-box',
    relativeAssetPath: 'assets/northstar_icons/Value=close-box, Filled=No.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'close-box-2',
    relativeAssetPath: 'assets/northstar_icons/Value=close-box, Filled=Yes.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'close-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=close-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'close-circle-2',
    relativeAssetPath: 'assets/northstar_icons/Value=close-circle, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'cloud-check',
    relativeAssetPath: 'assets/northstar_icons/Value=cloud-check, Solid=No.svg',
    category: NorthstarIconCategory.cloud,
  ),
  NorthstarIconManifestItem(
    id: 'cloud-download',
    relativeAssetPath: 'assets/northstar_icons/Value=cloud-download, Solid=No.svg',
    category: NorthstarIconCategory.cloud,
  ),
  NorthstarIconManifestItem(
    id: 'cloud-slash',
    relativeAssetPath: 'assets/northstar_icons/Value=cloud-slash, Solid=No.svg',
    category: NorthstarIconCategory.cloud,
  ),
  NorthstarIconManifestItem(
    id: 'cloud-upload',
    relativeAssetPath: 'assets/northstar_icons/Value=cloud-upload, Solid=No.svg',
    category: NorthstarIconCategory.cloud,
  ),
  NorthstarIconManifestItem(
    id: 'cloud-x',
    relativeAssetPath: 'assets/northstar_icons/Value=cloud-x, Solid=No.svg',
    category: NorthstarIconCategory.cloud,
  ),
  NorthstarIconManifestItem(
    id: 'columns',
    relativeAssetPath: 'assets/northstar_icons/Value=columns, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'comment',
    relativeAssetPath: 'assets/northstar_icons/Value=comment, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'comparison',
    relativeAssetPath: 'assets/northstar_icons/Value=comparison, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'copy',
    relativeAssetPath: 'assets/northstar_icons/Value=copy.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'credit-card',
    relativeAssetPath: 'assets/northstar_icons/Value=credit card, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'dashboard',
    relativeAssetPath: 'assets/northstar_icons/Value=dashboard, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'delete',
    relativeAssetPath: 'assets/northstar_icons/Value=delete, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'delivery',
    relativeAssetPath: 'assets/northstar_icons/Value=delivery, Solid=No.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'desktop',
    relativeAssetPath: 'assets/northstar_icons/Value=desktop, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'dislike',
    relativeAssetPath: 'assets/northstar_icons/Value=dislike, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'document-add',
    relativeAssetPath: 'assets/northstar_icons/Value=document-add.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-approve-2',
    relativeAssetPath: 'assets/northstar_icons/Value=document-approve.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-download',
    relativeAssetPath: 'assets/northstar_icons/Value=document-download.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-edit',
    relativeAssetPath: 'assets/northstar_icons/Value=document-edit.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-lock-2',
    relativeAssetPath: 'assets/northstar_icons/Value=document-lock.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-remove',
    relativeAssetPath: 'assets/northstar_icons/Value=document-remove.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-share',
    relativeAssetPath: 'assets/northstar_icons/Value=document-share.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-upload',
    relativeAssetPath: 'assets/northstar_icons/Value=document-upload.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'document-2',
    relativeAssetPath: 'assets/northstar_icons/Value=document.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'donut',
    relativeAssetPath: 'assets/northstar_icons/Value=donut, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'duplicate',
    relativeAssetPath: 'assets/northstar_icons/Value=duplicate.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'edit-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=edit chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'edit-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=edit chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'edit',
    relativeAssetPath: 'assets/northstar_icons/Value=edit, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'edit-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=edit-alt, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'ellipsis-2',
    relativeAssetPath: 'assets/northstar_icons/Value=ellipsis, Filled=No.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'email',
    relativeAssetPath: 'assets/northstar_icons/Value=email, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'empty',
    relativeAssetPath: 'assets/northstar_icons/Value=empty, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'empty-2',
    relativeAssetPath: 'assets/northstar_icons/Value=empty, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'english',
    relativeAssetPath: 'assets/northstar_icons/Value=english, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'envelope-check',
    relativeAssetPath: 'assets/northstar_icons/Value=envelope-check, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'exclamation',
    relativeAssetPath: 'assets/northstar_icons/Value=exclamation, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'external-link-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=external-link-alt, Filled=No.svg',
    category: NorthstarIconCategory.linking,
  ),
  NorthstarIconManifestItem(
    id: 'eye-hide',
    relativeAssetPath: 'assets/northstar_icons/Value=eye-hide, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'eye-show',
    relativeAssetPath: 'assets/northstar_icons/Value=eye-show, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'face-happy',
    relativeAssetPath: 'assets/northstar_icons/Value=face-happy, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'favorite-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=favorite chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'favorite',
    relativeAssetPath: 'assets/northstar_icons/Value=favorite, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'favorite-2',
    relativeAssetPath: 'assets/northstar_icons/Value=favorite, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'file-graph',
    relativeAssetPath: 'assets/northstar_icons/Value=file-graph, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'file-search-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=file-search-alt.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'filter',
    relativeAssetPath: 'assets/northstar_icons/Value=filter, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'flag-2',
    relativeAssetPath: 'assets/northstar_icons/Value=flag 2, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'folder-add',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-add.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-approve',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-approve.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'folder-download',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-download.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-edit',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-edit.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-lock',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-lock.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-remove',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-remove.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-share',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-share.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder-upload',
    relativeAssetPath: 'assets/northstar_icons/Value=folder-upload.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'folder',
    relativeAssetPath: 'assets/northstar_icons/Value=folder.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'gift-2',
    relativeAssetPath: 'assets/northstar_icons/Value=gift, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'hashtag',
    relativeAssetPath: 'assets/northstar_icons/Value=hashtag, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'heart',
    relativeAssetPath: 'assets/northstar_icons/Value=heart, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'heart-2',
    relativeAssetPath: 'assets/northstar_icons/Value=heart, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'heart-check',
    relativeAssetPath: 'assets/northstar_icons/Value=heart-check, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'heart-remove',
    relativeAssetPath: 'assets/northstar_icons/Value=heart-remove, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'heartbeat',
    relativeAssetPath: 'assets/northstar_icons/Value=heartbeat, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'help',
    relativeAssetPath: 'assets/northstar_icons/Value=help, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'hierarchy',
    relativeAssetPath: 'assets/northstar_icons/Value=hierarchy, Solid=No.svg',
    category: NorthstarIconCategory.direction,
  ),
  NorthstarIconManifestItem(
    id: 'home',
    relativeAssetPath: 'assets/northstar_icons/Value=home, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'hourglass',
    relativeAssetPath: 'assets/northstar_icons/Value=hourglass, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'hyperlink',
    relativeAssetPath: 'assets/northstar_icons/Value=hyperlink, Filled=No.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'image',
    relativeAssetPath: 'assets/northstar_icons/Value=image, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'image-2',
    relativeAssetPath: 'assets/northstar_icons/Value=image, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'image-add',
    relativeAssetPath: 'assets/northstar_icons/Value=image-add, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'image-broken',
    relativeAssetPath: 'assets/northstar_icons/Value=image-broken, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'important',
    relativeAssetPath: 'assets/northstar_icons/Value=important, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'important-2',
    relativeAssetPath: 'assets/northstar_icons/Value=important, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'info-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=info chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'info-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=info chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'information',
    relativeAssetPath: 'assets/northstar_icons/Value=information, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'information-2',
    relativeAssetPath: 'assets/northstar_icons/Value=information, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'internet',
    relativeAssetPath: 'assets/northstar_icons/Value=internet, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'invoice',
    relativeAssetPath: 'assets/northstar_icons/Value=invoice, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'joof-draft',
    relativeAssetPath: 'assets/northstar_icons/Value=joof-draft.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'joof-pending',
    relativeAssetPath: 'assets/northstar_icons/Value=joof-pending.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'joof-submitted',
    relativeAssetPath: 'assets/northstar_icons/Value=joof-submitted.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'kebab',
    relativeAssetPath: 'assets/northstar_icons/Value=kebab, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'key-skeleton-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=key-skeleton-alt, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'laptop',
    relativeAssetPath: 'assets/northstar_icons/Value=laptop, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'lightbulb',
    relativeAssetPath: 'assets/northstar_icons/Value=lightbulb, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'like',
    relativeAssetPath: 'assets/northstar_icons/Value=like, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'line-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=line chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'line-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=line chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'line-graph',
    relativeAssetPath: 'assets/northstar_icons/Value=line graph, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'link',
    relativeAssetPath: 'assets/northstar_icons/Value=link, Filled=No.svg',
    category: NorthstarIconCategory.arrows,
  ),
  NorthstarIconManifestItem(
    id: 'lock-2',
    relativeAssetPath: 'assets/northstar_icons/Value=lock, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'lock-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=lock-alt, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'love-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=love chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'medal',
    relativeAssetPath: 'assets/northstar_icons/Value=medal, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'meeting-board',
    relativeAssetPath: 'assets/northstar_icons/Value=meeting-board, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'megaphone-2',
    relativeAssetPath: 'assets/northstar_icons/Value=megaphone, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'mic',
    relativeAssetPath: 'assets/northstar_icons/Value=mic, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'mic-slash',
    relativeAssetPath: 'assets/northstar_icons/Value=mic-slash, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'mobile',
    relativeAssetPath: 'assets/northstar_icons/Value=mobile, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'money-stack',
    relativeAssetPath: 'assets/northstar_icons/Value=money-stack, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'moon',
    relativeAssetPath: 'assets/northstar_icons/Value=moon, Solid=No.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'moon-2',
    relativeAssetPath: 'assets/northstar_icons/Value=moon, Solid=Yes.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'moonset',
    relativeAssetPath: 'assets/northstar_icons/Value=moonset, Solid=No.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'moonset-2',
    relativeAssetPath: 'assets/northstar_icons/Value=moonset, Solid=Yes.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'mountains',
    relativeAssetPath: 'assets/northstar_icons/Value=mountains, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'mouse',
    relativeAssetPath: 'assets/northstar_icons/Value=mouse, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'neutral-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=neutral-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'new',
    relativeAssetPath: 'assets/northstar_icons/Value=new, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'notes',
    relativeAssetPath: 'assets/northstar_icons/Value=notes, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'offer-rejected',
    relativeAssetPath: 'assets/northstar_icons/Value=offer-rejected.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'offer-sent',
    relativeAssetPath: 'assets/northstar_icons/Value=offer-sent.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'office-bag',
    relativeAssetPath: 'assets/northstar_icons/Value=office bag, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'office-building-2',
    relativeAssetPath: 'assets/northstar_icons/Value=office building, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'panel-add',
    relativeAssetPath: 'assets/northstar_icons/Value=panel-add, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'pause-button',
    relativeAssetPath: 'assets/northstar_icons/Value=pause button, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'percentage',
    relativeAssetPath: 'assets/northstar_icons/Value=percentage, Filled=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'percentage-2',
    relativeAssetPath: 'assets/northstar_icons/Value=percentage, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'phone',
    relativeAssetPath: 'assets/northstar_icons/Value=phone, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'pie-chart',
    relativeAssetPath: 'assets/northstar_icons/Value=pie chart, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'pin-location',
    relativeAssetPath: 'assets/northstar_icons/Value=pin-location, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'play',
    relativeAssetPath: 'assets/northstar_icons/Value=play, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'play-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=play-circle, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'processor',
    relativeAssetPath: 'assets/northstar_icons/Value=processor, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'proposal-requested',
    relativeAssetPath: 'assets/northstar_icons/Value=proposal-requested.svg',
    category: NorthstarIconCategory.processFolder,
  ),
  NorthstarIconManifestItem(
    id: 'qr-scan',
    relativeAssetPath: 'assets/northstar_icons/Value=qr-scan, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'question',
    relativeAssetPath: 'assets/northstar_icons/Value=question, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'question-circle-2',
    relativeAssetPath: 'assets/northstar_icons/Value=question-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'question-circle-3',
    relativeAssetPath: 'assets/northstar_icons/Value=question-circle, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'record-audio',
    relativeAssetPath: 'assets/northstar_icons/Value=record-audio, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'reload-2',
    relativeAssetPath: 'assets/northstar_icons/Value=reload, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'remove',
    relativeAssetPath: 'assets/northstar_icons/Value=remove, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'remove-box',
    relativeAssetPath: 'assets/northstar_icons/Value=remove-box, Filled=No.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'remove-box-2',
    relativeAssetPath: 'assets/northstar_icons/Value=remove-box, Filled=Yes.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'remove-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=remove-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'remove-circle-2',
    relativeAssetPath: 'assets/northstar_icons/Value=remove-circle, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'search',
    relativeAssetPath: 'assets/northstar_icons/Value=search, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'send',
    relativeAssetPath: 'assets/northstar_icons/Value=send, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'server-network',
    relativeAssetPath: 'assets/northstar_icons/Value=server-network, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'settings',
    relativeAssetPath: 'assets/northstar_icons/Value=settings, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'share',
    relativeAssetPath: 'assets/northstar_icons/Value=share, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'share-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=share-alt, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'share-alt-2',
    relativeAssetPath: 'assets/northstar_icons/Value=share-alt, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'shopping-bag',
    relativeAssetPath: 'assets/northstar_icons/Value=shopping bag, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'sitemap',
    relativeAssetPath: 'assets/northstar_icons/Value=sitemap, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'sliders-v-alt',
    relativeAssetPath: 'assets/northstar_icons/Value=sliders-v-alt, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'social-media',
    relativeAssetPath: 'assets/northstar_icons/Value=social-media, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'sparkle',
    relativeAssetPath: 'assets/northstar_icons/Value=sparkle, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'sun',
    relativeAssetPath: 'assets/northstar_icons/Value=sun, Solid=No.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'sun-2',
    relativeAssetPath: 'assets/northstar_icons/Value=sun, Solid=Yes.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'sunset',
    relativeAssetPath: 'assets/northstar_icons/Value=sunset, Solid=No.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'sunset-2',
    relativeAssetPath: 'assets/northstar_icons/Value=sunset, Solid=Yes.svg',
    category: NorthstarIconCategory.weather,
  ),
  NorthstarIconManifestItem(
    id: 'table',
    relativeAssetPath: 'assets/northstar_icons/Value=table, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'tag',
    relativeAssetPath: 'assets/northstar_icons/Value=tag, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'target',
    relativeAssetPath: 'assets/northstar_icons/Value=target, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'thumbnail-2',
    relativeAssetPath: 'assets/northstar_icons/Value=thumbnail, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'ticket',
    relativeAssetPath: 'assets/northstar_icons/Value=ticket, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'toga-hat',
    relativeAssetPath: 'assets/northstar_icons/Value=toga hat, Solid=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'typing-chat',
    relativeAssetPath: 'assets/northstar_icons/Value=typing chat, Style=board, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'typing-chat-2',
    relativeAssetPath: 'assets/northstar_icons/Value=typing chat, Style=bubble, Solid=No.svg',
    category: NorthstarIconCategory.chat,
  ),
  NorthstarIconManifestItem(
    id: 'unlink',
    relativeAssetPath: 'assets/northstar_icons/Value=unlink, Filled=No.svg',
    category: NorthstarIconCategory.linking,
  ),
  NorthstarIconManifestItem(
    id: 'unlock',
    relativeAssetPath: 'assets/northstar_icons/Value=unlock, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'unlock-2',
    relativeAssetPath: 'assets/northstar_icons/Value=unlock, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'user-2',
    relativeAssetPath: 'assets/northstar_icons/Value=user, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'user-box',
    relativeAssetPath: 'assets/northstar_icons/Value=user-box, Filled=No.svg',
    category: NorthstarIconCategory.shipping,
  ),
  NorthstarIconManifestItem(
    id: 'user-check',
    relativeAssetPath: 'assets/northstar_icons/Value=user-check, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'user-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=user-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'user-group-2',
    relativeAssetPath: 'assets/northstar_icons/Value=user-group, Filled=No.svg',
    category: NorthstarIconCategory.realTime,
  ),
  NorthstarIconManifestItem(
    id: 'user-plus',
    relativeAssetPath: 'assets/northstar_icons/Value=user-plus, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'video',
    relativeAssetPath: 'assets/northstar_icons/Value=video, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'video-slash',
    relativeAssetPath: 'assets/northstar_icons/Value=video-slash, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'volume-mute',
    relativeAssetPath: 'assets/northstar_icons/Value=volume-mute, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'wallet',
    relativeAssetPath: 'assets/northstar_icons/Value=wallet, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'warning',
    relativeAssetPath: 'assets/northstar_icons/Value=warning, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'warning-2',
    relativeAssetPath: 'assets/northstar_icons/Value=warning, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'warning-circle',
    relativeAssetPath: 'assets/northstar_icons/Value=warning-circle, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'warning-circle-2',
    relativeAssetPath: 'assets/northstar_icons/Value=warning-circle, Filled=Yes.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'wifi',
    relativeAssetPath: 'assets/northstar_icons/Value=wifi, Solid=No.svg',
    category: NorthstarIconCategory.multimedia,
  ),
  NorthstarIconManifestItem(
    id: 'withdrawal',
    relativeAssetPath: 'assets/northstar_icons/Value=withdrawal, Solid=No.svg',
    category: NorthstarIconCategory.statistics,
  ),
  NorthstarIconManifestItem(
    id: 'wrench',
    relativeAssetPath: 'assets/northstar_icons/Value=wrench, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'zoom-in',
    relativeAssetPath: 'assets/northstar_icons/Value=zoom-in, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'zoom-out',
    relativeAssetPath: 'assets/northstar_icons/Value=zoom-out, Filled=No.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'draggabledots-1',
    relativeAssetPath: 'assets/northstar_icons/draggabledots 1.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'hide_sidebar_horizontal_icon_128227-1',
    relativeAssetPath: 'assets/northstar_icons/hide_sidebar_horizontal_icon_128227 1.svg',
    category: NorthstarIconCategory.userInterface,
  ),
  NorthstarIconManifestItem(
    id: 'show_sidebar_horizontal_icon_128225-1',
    relativeAssetPath: 'assets/northstar_icons/show_sidebar_horizontal_icon_128225 1.svg',
    category: NorthstarIconCategory.userInterface,
  ),
];
