// Run from package root:
//   dart run tool/generate_northstar_icon_manifest.dart
//
// Regenerates lib/src/icons/northstar_icon_manifest.g.dart after adding SVGs.

import 'dart:io';

void main() {
  final Directory packageRoot = Directory.current;
  final Directory iconRoot = Directory('${packageRoot.path}/assets/northstar_icons');
  if (!iconRoot.existsSync()) {
    stderr.writeln('Missing ${iconRoot.path}');
    exit(1);
  }

  final List<File> files = iconRoot
      .listSync(recursive: true)
      .whereType<File>()
      .where((File f) => f.path.endsWith('.svg'))
      .toList()
    ..sort((File a, File b) => a.path.compareTo(b.path));

  final Map<String, int> idCount = <String, int>{};
  final List<_Entry> entries = <_Entry>[];

  for (final File f in files) {
    final String rel = f.path
        .substring(packageRoot.path.length + 1)
        .replaceAll(r'\', '/');
    final String base = rel.split('/').last;
    String id = _deriveId(base, rel);
    idCount[id] = (idCount[id] ?? 0) + 1;
    if (idCount[id]! > 1) {
      id = '$id-${idCount[id]}';
    }
    final NorthstarIconCategory cat = _categorize(rel, base.toLowerCase(), id.toLowerCase());
    entries.add(_Entry(id: id, relativeAssetPath: rel, category: cat));
  }

  final StringBuffer out = StringBuffer()
    ..writeln('// GENERATED BY tool/generate_northstar_icon_manifest.dart — DO NOT EDIT.')
    ..writeln()
    ..writeln("import 'northstar_icon_category.dart';")
    ..writeln("import 'northstar_icon_manifest_item.dart';")
    ..writeln()
    ..writeln('/// All bundled Northstar V3 SVGs under `assets/northstar_icons/`.')
    ..writeln('const List<NorthstarIconManifestItem> kNorthstarIconManifest = ')
    ..writeln('    <NorthstarIconManifestItem>[');

  for (final _Entry e in entries) {
    out.writeln('  NorthstarIconManifestItem(');
    out.writeln("    id: ${_dq(e.id)},");
    out.writeln("    relativeAssetPath: ${_dq(e.relativeAssetPath)},");
    out.writeln('    category: NorthstarIconCategory.${e.category.name},');
    out.writeln('  ),');
  }

  out.writeln('];');

  final File target = File('${packageRoot.path}/lib/src/icons/northstar_icon_manifest.g.dart');
  target.writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${entries.length} entries → ${target.path}');
}

class _Entry {
  _Entry({
    required this.id,
    required this.relativeAssetPath,
    required this.category,
  });

  final String id;
  final String relativeAssetPath;
  final NorthstarIconCategory category;
}

String _dq(String s) {
  return "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'")}'";
}

String _deriveId(String baseName, String relativePath) {
  String name = baseName;
  if (name.toLowerCase().endsWith('.svg')) {
    name = name.substring(0, name.length - 4);
  }
  if (name.startsWith('Icon=')) {
    name = name.substring(5);
  } else if (name.startsWith('Property 1=')) {
    name = name.substring(11);
  } else {
    final RegExpMatch? vm = RegExp(r'Value=([^,]+)').firstMatch(name);
    if (vm != null) {
      name = vm.group(1)!.trim();
    }
  }
  String slug = name
      .toLowerCase()
      .replaceAll(RegExp(r'\s+'), '-')
      .replaceAll(RegExp(r'[^a-z0-9._-]+'), '-')
      .replaceAll(RegExp(r'-+'), '-')
      .replaceAll(RegExp(r'^-|-\$'), '');
  if (slug.isEmpty) {
    slug = relativePath.hashCode.toRadixString(16);
  }
  if (relativePath.toLowerCase().contains('science/')) {
    slug = 'science-$slug';
  }
  return slug;
}

// ignore_for_file: avoid_slow_async_io

enum NorthstarIconCategory {
  arrows,
  userInterface,
  realTime,
  processFolder,
  chat,
  statistics,
  content,
  calendar,
  direction,
  multimedia,
  shipping,
  weather,
  cloud,
  linking,
  social,
  bomList,
  science,
  other,
}

bool _has(String blob, List<String> keys) {
  for (final String k in keys) {
    if (blob.contains(k)) {
      return true;
    }
  }
  return false;
}

NorthstarIconCategory _categorize(String rel, String fileLower, String id) {
  final String blob = '$rel $fileLower $id'.toLowerCase();

  if (rel.contains('Science/') || rel.toLowerCase().contains('/science/')) {
    return NorthstarIconCategory.science;
  }

  if (_has(blob, <String>[
        'align-',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'text-strike',
        'text-size',
        'font.svg',
        'heading',
        'list-ol',
        'list-ul',
        'redo',
        'undo',
        'rotating',
        'scale',
        'line-height',
      ])) {
    return NorthstarIconCategory.content;
  }

  if (_has(blob, <String>['chat', 'typing chat', 'line chat', 'bullet chat', 'approve chat', 'alert chat', 'edit chat', 'info chat', 'favorite chat', 'blank chat', 'comment'])) {
    return NorthstarIconCategory.chat;
  }

  if (_has(blob, <String>[
        'bar-graph',
        'pie-chart',
        'pie chart',
        'line-graph',
        'percentage',
        'bank',
        'expenses',
        'balance',
        'withdraw',
        'office-bag',
        'office-building',
        'check-card',
        'calculator',
        'bill',
        'notes',
      ])) {
    return NorthstarIconCategory.statistics;
  }

  if (_has(blob, <String>[
        'folder-add',
        'folder-edit',
        'folder-remove',
        'folder-check',
        'folder-download',
        'folder-share',
        'folder-upload',
        'folder-lock',
        'duplicate-folder',
        'path-finding',
        'post-deck',
        'post-outreach',
        'proposal',
        'under-review',
        'offer-',
        'file-expired',
        'document-add',
        'document-edit',
        'document-remove',
        'document-check',
        'document-download',
        'document-share',
        'document-upload',
        'document-lock',
        'document-approve',
        'document-reject',
      ]) ||
      (blob.contains('folder') && blob.contains('icon=')) ||
      (blob.contains('document') && blob.contains('icon=') && !blob.contains('chat'))) {
    return NorthstarIconCategory.processFolder;
  }

  if (_has(blob, <String>[
        'directory-team',
        'user-group',
        'user-less',
        'user-more',
        'user-stay',
        'user-time',
        'work-time',
        'common-group',
        'text-less',
        'text-more',
        'document-group',
        'check-group',
        'quarter-view',
        '3d-locker',
        'front-view',
        'price-tagging',
        'magazine',
        'leave-team',
      ])) {
    return NorthstarIconCategory.realTime;
  }

  if (_has(blob, <String>[
        'calendar',
        'stop-watch',
        'clock-add',
        'clock-group',
        'timezone',
        'time-add',
        'calendar-heart',
      ]) ||
      rel.contains('Icon=clock.svg')) {
    return NorthstarIconCategory.calendar;
  }

  if (_has(blob, <String>[
        'map-pin',
        'hierarchy',
        'expand-all',
        'orientation',
        'castle',
        'point',
        'place',
      ])) {
    return NorthstarIconCategory.direction;
  }

  if (_has(blob, <String>[
        'play-circle',
        'video-slash',
        'video',
        'mic-slash',
        'mic',
        'headset',
        'monitor',
        'tablet',
        'cellphone',
        'mobile',
        'desktop',
        'wifi',
        'volume',
        'repeat',
        'shuffle',
        'skip-',
        'record-audio',
        'mountains',
        'ticket',
        'processor',
        'mouse',
        'play',
        'pause',
      ])) {
    return NorthstarIconCategory.multimedia;
  }

  if (_has(blob, <String>['shipped', 'delivery-car', 'delivery', 'shipped-box']) ||
      (blob.contains('box') && blob.contains('value='))) {
    return NorthstarIconCategory.shipping;
  }

  if (_has(blob, <String>['rain', 'snow', 'thunder', 'moonset', 'sunset', 'moon', 'sun', 'clouds'])) {
    return NorthstarIconCategory.weather;
  }

  if (_has(blob, <String>['cloud-upload', 'cloud-download', 'cloud-check', 'cloud-remove', 'cloud-lock', 'cloud-slash', 'cloud-x', 'value=cloud'])) {
    return NorthstarIconCategory.cloud;
  }

  if (_has(blob, <String>['external-link', 'unlink'])) {
    return NorthstarIconCategory.linking;
  }

  if (_has(blob, <String>[
        'facebook',
        'instagram',
        'linkedin',
        'twitter',
        'youtube',
        'messenger',
        'telegram',
        'property 1=x.svg',
        '/x.svg',
      ]) ||
      id == 'x' && fileLower.contains('property')) {
    return NorthstarIconCategory.social;
  }

  if (_has(blob, <String>['database', 'terminal', 'restore', 'bom'])) {
    return NorthstarIconCategory.bomList;
  }

  if (_has(blob, <String>[
        'arrow',
        'chevron',
        'download',
        'upload',
        'refresh',
        'login',
        'logout',
        'sort',
        'maximize',
        'minimize',
        'expand',
        'collapse',
        'switch-vertical',
        'switch-horizontal',
        'spin',
        'activate-from',
        'exit-full',
        'spinner',
        'ellipsis',
      ]) ||
      (blob.contains('link') && !blob.contains('external') && !blob.contains('unlink') && !blob.contains('chat'))) {
    return NorthstarIconCategory.arrows;
  }

  if (_has(blob, <String>[
        'atom',
        'molecule',
        'organism',
        'brain',
        'foundation',
        'template',
        'medical',
      ])) {
    return NorthstarIconCategory.science;
  }

  return NorthstarIconCategory.userInterface;
}
